<a href="https://colab.research.google.com/github/purosh96/NeuralNetwork/blob/main/Iris_SingleLayer_TF1X.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
from google.colab import files
upload = files.upload()

Saving iris.csv to iris (1).csv


In [15]:
df = pd.read_csv("iris.csv")
df.shape

(150, 5)

In [16]:
df.head()

petallength  petalwidth  sepallength  sepalwidth  species
0          5.1         3.5          1.4         0.2        0
1          4.9         3.0          1.4         0.2        0
2          4.7         3.2          1.3         0.2        0
3          4.6         3.1          1.5         0.2        0
4          5.0         3.6          1.4         0.2        0

In [20]:
X = df.drop(labels=["species"],axis=1)
Y = df["species"]
X.shape,Y.shape

((150, 4), (150,))

In [24]:
Y_hot = pd.get_dummies(Y)
Y_hot.head()

0  1  2
0  1  0  0
1  1  0  0
2  1  0  0
3  1  0  0
4  1  0  0

In [25]:
Y_hot = Y_hot.values

In [10]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [11]:
import tensorflow as tf
tf.__version__

'1.15.2'

In [29]:
x_train = tf.placeholder(tf.float32,shape=[150,4])
y_train = tf.placeholder(tf.float32,shape=[150,3])

In [30]:
weights = tf.Variable(tf.truncated_normal([4,3],stddev=0.1))
bias = tf.Variable(tf.truncated_normal([3],stddev=0.1))

In [33]:
I = tf.add(tf.matmul(x_train,weights),bias)
O = tf.nn.softmax(I)

In [34]:
individual_loss = tf.nn.softmax_cross_entropy_with_logits_v2(labels = y_train,logits = O)
loss = tf.reduce_mean(individual_loss)

In [35]:
gdo = tf.train.GradientDescentOptimizer(learning_rate=0.5)
train = gdo.minimize(loss)

In [36]:
init = tf.global_variables_initializer()

In [37]:
sess = tf.Session()

In [38]:
sess.run(init)

In [46]:
sess.run(weights)

array([[ 0.6514709 ,  0.25174946, -0.71497273],
       [ 1.022862  , -0.3835781 , -0.83518463],
       [-1.6312286 ,  0.02537882,  1.7283113 ],
       [-0.72613007, -0.46437344,  1.2038046 ]], dtype=float32)

In [47]:
sess.run(bias)

array([ 0.19718105,  0.04517436, -0.4118081 ], dtype=float32)

In [55]:
for i in range(10000):
  sess.run(train,feed_dict={x_train:X,y_train:Y_hot})

In [56]:
result = sess.run(O,feed_dict={x_train:X})
type(result)

numpy.ndarray

In [57]:
Y_Pred = sess.run(tf.argmax(result,1))

In [58]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [59]:
accuracy_score(Y,Y_Pred)

0.98

In [60]:
confusion_matrix(Y,Y_Pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  0, 50]])